# -*- coding: utf-8 -*-
"""Laboratorio #2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BnHMKarDAtHuj15Rg2vjhJBUaqyHiU1W
"""

#Apertura de archivo
import pandas as pd
import math
df=pd.read_csv('/casasboston.csv')
data=pd.DataFrame(df)
print(data)
print(data.AGE)

#1 Seleccionar TOWN
#2 TOWN: CRIM aquellos casos que son superiores a 0.50
#3 Sacar el promedio de la edad usar función AVG de matemática
#4 Imprimio un índice y una edad, retorna los puntos correspodientes
#5 Ordenamiento pot CRIM // sort para el ordenamiento

#1 Seleccionar TOWN
print("DATA TOWN")
dataTowm = data.loc[(data['TOWN']=="Winthrop")]
print(dataTowm)

#2 TOWN: CRIM aquellos casos que son superiores a 0.50
print("DATA CRIM")
dataTowm = data.loc[(data['TOWN']=="Winthrop")]
dataCrim = dataTowm.loc[(data['CRIM']>=0.50)]
print(dataCrim)

#3 Sacar el promedio de la edad usar función AVG de matemática
import statistics
print("DATA EDAD")
dataEdad = data.AGE
promedio= statistics.mean(dataEdad)
print(promedio)

#4 Imprimio un índice y una edad, retorna los puntos correspodientes
print("DATA ÍNDICE Y EDAD")
dataPtratio = data.loc[(data['PTRATIO']<=20)]
dataPuntos= dataPtratio.loc[(data['AGE']<=20)]
print(dataPuntos)

#5 Ordenamiento por CRIM // sort para el ordenamiento
dataTowm = data.loc[(data['TOWN']=="Winthrop")]
print("DATA ORDENAMIENTO")
dataOrdenamiento= sorted(data[(data['TOWN']=="Winthrop")]['CRIM'])
print(dataOrdenamiento)